# Generated by Django 2.2 on 2019-05-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_pet_owners'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='owners',
            field=models.ManyToManyField(related_name='pets', to='myapp.Owner'),
        ),
    ]
