# Generated by Django 2.2 on 2019-05-21 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_pet_owners'),
    ]

    operations = [
        migrations.CreateModel(
            name='Join',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='myapp.Pet')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='myapp.Owner')),
            ],
        ),
    ]
