# Generated by Django 2.2 on 2019-05-21 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_join'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Join',
        ),
    ]
