# Generated by Django 2.2 on 2019-05-22 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_join'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Join',
        ),
    ]
