# Generated by Django 2.2 on 2019-05-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_join'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='password',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
